import { randomBytes, scrypt, timingSafeEqual } from "node:crypto";

/**
 * The account "secret key": generated by us (never user-chosen, so no weak or reused passwords), 160 bits, shown once.
 * Looks like  pcs_ABCD-EFGH-JKMN-PQRS-TVWX-YZ23-4567-89AB  (Crockford base32: no I, L, O, U).
 * Only a salted scrypt hash is stored.
 */
const ALPHABET = "0123456789ABCDEFGHJKMNPQRSTVWXYZ";
const SECRET_CHARS = 32;

function base32(buf: Buffer): string {
  let bits = 0;
  let value = 0;
  let out = "";
  for (const byte of buf) {
    value = (value << 8) | byte;
    bits += 8;
    while (bits >= 5) {
      out += ALPHABET[(value >>> (bits - 5)) & 31];
      bits -= 5;
    }
  }
  return out;
}

export function generateSecretKey(): string {
  const raw = base32(randomBytes(20)); // 20 bytes = 160 bits = exactly 32 base32 chars
  return `pcs_${raw.match(/.{4}/g)!.join("-")}`;
}

/** Forgiving about what people type: case, dashes, spaces, the pcs_ prefix, and Crockford look-alikes (O→0, I/L→1). Null if malformed. */
export function normalizeSecretKey(input: unknown): string | null {
  if (typeof input !== "string") return null;
  let s = input.trim().toUpperCase().replace(/^PCS[_-]?/, "").replace(/[\s-]/g, "");
  s = s.replace(/O/g, "0").replace(/[IL]/g, "1");
  return s.length === SECRET_CHARS && [...s].every((c) => ALPHABET.includes(c)) ? s : null;
}

const N = 16384; // 16 MiB: affordable on a small free instance, and the key has 160 bits of entropy anyway
const R = 8;
const P = 1;
const KEYLEN = 32;

const scryptAsync = (secret: string, salt: Buffer, n = N, r = R, p = P) =>
  new Promise<Buffer>((resolve, reject) => scrypt(secret, salt, KEYLEN, { N: n, r, p, maxmem: 64 * 1024 * 1024 }, (e, k) => (e ? reject(e) : resolve(k))));

/** Hashes a (normalized) secret key. Runs on the libuv threadpool, so it doesn't block the event loop. */
export async function hashSecretKey(normalized: string): Promise<string> {
  const salt = randomBytes(16);
  const hash = await scryptAsync(normalized, salt);
  return `scrypt$${N}$${R}$${P}$${salt.toString("base64")}$${hash.toString("base64")}`;
}

export async function verifySecretKey(input: unknown, stored: string): Promise<boolean> {
  const normalized = normalizeSecretKey(input);
  const parts = stored.split("$");
  if (parts.length !== 6 || parts[0] !== "scrypt") return false;
  const [n, r, p] = [Number(parts[1]), Number(parts[2]), Number(parts[3])];
  if (![n, r, p].every(Number.isInteger)) return false;
  // Always do the work, even for a malformed guess, so timing doesn't reveal which check failed.
  const expected = Buffer.from(parts[5], "base64");
  const got = await scryptAsync(normalized ?? "invalid", Buffer.from(parts[4], "base64"), n, r, p);
  return normalized !== null && got.length === expected.length && timingSafeEqual(got, expected);
}

let dummy: Promise<string> | undefined;
/** Verify against a throwaway hash when the username doesn't exist, so "unknown user" costs the same as "wrong key". */
export async function burnVerify(input: unknown): Promise<void> {
  dummy ??= hashSecretKey("0".repeat(SECRET_CHARS));
  await verifySecretKey(input, await dummy);
}

export const maskSecretKey = (s: string) => `${s.slice(0, 8)}…`;
