-- Paperclip Bridge — complete schema for Supabase.
-- GENERATED by `npm run admin -- schema-sql` from migrations/*.sql. Do not edit by hand.
--
-- How to use: Supabase dashboard → SQL Editor → New query → paste this whole file → Run.
-- Safe to run more than once. Afterwards `npm run migrate` reports "up to date" because the migrations are recorded below.
-- Then (recommended) create the least-privilege app role: see docs/least-privilege.sql.

begin;

-- ───── 001_init.sql ─────
-- Paperclip Bridge schema. Run with a direct/session connection (see docs/DEPLOY-RENDER.md).
-- Everything lives in its own schema, which Supabase does NOT expose through its REST/GraphQL Data API,
-- and is additionally locked down with RLS (no policies = deny) and revoked grants, so the public `anon`
-- key can never read it. The bridge connects as a privileged role over a normal Postgres connection.

create schema if not exists bridge;

create table if not exists bridge.clients (
  id           text primary key,
  name         text   not null,
  redirect_uris text[] not null,
  created_at   bigint not null,
  last_used_at bigint not null
);

create table if not exists bridge.grants (
  id                text primary key,
  client_id         text   not null,
  client_name       text   not null,
  user_id           text,
  scopes            text[] not null,
  resource          text   not null,
  instance_url      text,
  sealed_credential text,           -- AES-256-GCM sealed in the app; the key never touches the database
  created_at        bigint not null,
  last_used_at      bigint not null,
  revoked           boolean not null default false
);
create index if not exists grants_idle_idx on bridge.grants (last_used_at) where not revoked;

create table if not exists bridge.tokens (
  hash       text primary key,       -- sha256 of the raw token; raw tokens are never stored
  kind       text   not null check (kind in ('access', 'refresh')),
  grant_id   text   not null,
  expires_at bigint not null,
  consumed   boolean not null default false
);
create index if not exists tokens_grant_idx on bridge.tokens (grant_id);
create index if not exists tokens_expiry_idx on bridge.tokens (expires_at);

create table if not exists bridge.pending (
  rid        text primary key,
  data       jsonb  not null,        -- sensitive parts already sealed by the app
  expires_at bigint not null
);
create index if not exists pending_expiry_idx on bridge.pending (expires_at);

create table if not exists bridge.codes (
  hash       text primary key,
  data       jsonb  not null,
  expires_at bigint not null,
  used       boolean not null default false,
  grant_id   text
);
create index if not exists codes_expiry_idx on bridge.codes (expires_at);

create table if not exists bridge.rate_limits (
  key      text primary key,
  n        integer not null,
  reset_at bigint  not null
);

-- Defence in depth: deny by default for every non-owner role.
alter table bridge.clients     enable row level security;
alter table bridge.grants      enable row level security;
alter table bridge.tokens      enable row level security;
alter table bridge.pending     enable row level security;
alter table bridge.codes       enable row level security;
alter table bridge.rate_limits enable row level security;

revoke all on schema bridge from public;
revoke all on all tables in schema bridge from public;

do $$
declare r text;
begin
  foreach r in array array['anon', 'authenticated'] loop
    if exists (select 1 from pg_roles where rolname = r) then
      execute format('revoke all on schema bridge from %I', r);
      execute format('revoke all on all tables in schema bridge from %I', r);
      execute format('alter default privileges in schema bridge revoke all on tables from %I', r);
    end if;
  end loop;
end $$;

-- ───── 002_audit.sql ─────
-- Audit & latency telemetry. One row per tool call and per OAuth/MCP HTTP request.
-- NEVER contains tool arguments, tool results, tokens or credentials: only who/what/how-long/outcome.
-- Retention is enforced by the app (BRIDGE_AUDIT_RETENTION_DAYS, default 30); rows hold the user id and tenant host, so keep it short.

create table if not exists bridge.audit_events (
  id             bigint generated always as identity primary key,
  ts             bigint  not null,                      -- ms since epoch (UTC)
  node           text    not null,                      -- which bridge instance wrote it
  kind           text    not null check (kind in ('tool', 'http')),
  name           text    not null,                      -- tool name, or route group such as 'oauth.token'
  mutation       boolean not null default false,
  ok             boolean not null,
  status         integer,
  error_class    text,                                  -- invalid_input | insufficient_scope | read_only | upstream_4xx | upstream_5xx | upstream_unreachable | rate_limited | unauthorized | internal
  total_ms       integer not null,                      -- end to end inside the bridge
  upstream_ms    integer,                               -- of which: waiting on the user's Paperclip (union of parallel requests)
  upstream_calls integer,
  scope          text,                                  -- scope the call required
  grant_id       text,
  client         text,
  instance       text,                                  -- tenant Paperclip host
  user_id        text
);

create index if not exists audit_ts_idx          on bridge.audit_events (ts desc);
create index if not exists audit_kind_name_idx   on bridge.audit_events (kind, name, ts desc);
create index if not exists audit_instance_idx    on bridge.audit_events (instance, ts desc) where instance is not null;
create index if not exists audit_errors_idx      on bridge.audit_events (ts desc) where not ok;

alter table bridge.audit_events enable row level security;
revoke all on bridge.audit_events from public;

do $$
declare r text;
begin
  foreach r in array array['anon', 'authenticated'] loop
    if exists (select 1 from pg_roles where rolname = r) then
      execute format('revoke all on bridge.audit_events from %I', r);
    end if;
  end loop;
end $$;

-- ───── migration bookkeeping ─────
create table if not exists bridge.schema_migrations (version text primary key, applied_at timestamptz not null default now());
alter table bridge.schema_migrations enable row level security;
revoke all on bridge.schema_migrations from public;
do $$ declare r text; begin
  foreach r in array array['anon', 'authenticated'] loop
    if exists (select 1 from pg_roles where rolname = r) then execute format('revoke all on bridge.schema_migrations from %I', r); end if;
  end loop;
end $$;
insert into bridge.schema_migrations (version) values ('001_init.sql'), ('002_audit.sql') on conflict (version) do nothing;

commit;
