-- Paperclip Bridge — complete schema for Supabase.
-- GENERATED by `npm run admin -- schema-sql` from migrations/*.sql. Do not edit by hand.
--
-- How to use: Supabase dashboard → SQL Editor → New query → paste this whole file → Run.
-- Safe to run more than once. Afterwards `npm run migrate` reports "up to date" because the migrations are recorded below.
-- Then (recommended) create the least-privilege app role: see docs/least-privilege.sql.

begin;

-- ───── 001_init.sql ─────
-- Paperclip Bridge schema. Run with a direct/session connection (see docs/DEPLOY-RENDER.md).
-- Everything lives in its own schema, which Supabase does NOT expose through its REST/GraphQL Data API,
-- and is additionally locked down with RLS (no policies = deny) and revoked grants, so the public `anon`
-- key can never read it. The bridge connects as a privileged role over a normal Postgres connection.

create schema if not exists bridge;

create table if not exists bridge.clients (
  id           text primary key,
  name         text   not null,
  redirect_uris text[] not null,
  created_at   bigint not null,
  last_used_at bigint not null
);

create table if not exists bridge.grants (
  id                text primary key,
  client_id         text   not null,
  client_name       text   not null,
  user_id           text,
  scopes            text[] not null,
  resource          text   not null,
  instance_url      text,
  sealed_credential text,           -- AES-256-GCM sealed in the app; the key never touches the database
  created_at        bigint not null,
  last_used_at      bigint not null,
  revoked           boolean not null default false
);
create index if not exists grants_idle_idx on bridge.grants (last_used_at) where not revoked;

create table if not exists bridge.tokens (
  hash       text primary key,       -- sha256 of the raw token; raw tokens are never stored
  kind       text   not null check (kind in ('access', 'refresh')),
  grant_id   text   not null,
  expires_at bigint not null,
  consumed   boolean not null default false
);
create index if not exists tokens_grant_idx on bridge.tokens (grant_id);
create index if not exists tokens_expiry_idx on bridge.tokens (expires_at);

create table if not exists bridge.pending (
  rid        text primary key,
  data       jsonb  not null,        -- sensitive parts already sealed by the app
  expires_at bigint not null
);
create index if not exists pending_expiry_idx on bridge.pending (expires_at);

create table if not exists bridge.codes (
  hash       text primary key,
  data       jsonb  not null,
  expires_at bigint not null,
  used       boolean not null default false,
  grant_id   text
);
create index if not exists codes_expiry_idx on bridge.codes (expires_at);

create table if not exists bridge.rate_limits (
  key      text primary key,
  n        integer not null,
  reset_at bigint  not null
);

-- Defence in depth: deny by default for every non-owner role.
alter table bridge.clients     enable row level security;
alter table bridge.grants      enable row level security;
alter table bridge.tokens      enable row level security;
alter table bridge.pending     enable row level security;
alter table bridge.codes       enable row level security;
alter table bridge.rate_limits enable row level security;

revoke all on schema bridge from public;
revoke all on all tables in schema bridge from public;

do $$
declare r text;
begin
  foreach r in array array['anon', 'authenticated'] loop
    if exists (select 1 from pg_roles where rolname = r) then
      execute format('revoke all on schema bridge from %I', r);
      execute format('revoke all on all tables in schema bridge from %I', r);
      execute format('alter default privileges in schema bridge revoke all on tables from %I', r);
    end if;
  end loop;
end $$;

-- ───── 002_audit.sql ─────
-- Audit & latency telemetry. One row per tool call and per OAuth/MCP HTTP request.
-- NEVER contains tool arguments, tool results, tokens or credentials: only who/what/how-long/outcome.
-- Retention is enforced by the app (BRIDGE_AUDIT_RETENTION_DAYS, default 30); rows hold the user id and tenant host, so keep it short.

create table if not exists bridge.audit_events (
  id             bigint generated always as identity primary key,
  ts             bigint  not null,                      -- ms since epoch (UTC)
  node           text    not null,                      -- which bridge instance wrote it
  kind           text    not null check (kind in ('tool', 'http')),
  name           text    not null,                      -- tool name, or route group such as 'oauth.token'
  mutation       boolean not null default false,
  ok             boolean not null,
  status         integer,
  error_class    text,                                  -- invalid_input | insufficient_scope | read_only | upstream_4xx | upstream_5xx | upstream_unreachable | rate_limited | unauthorized | internal
  total_ms       integer not null,                      -- end to end inside the bridge
  upstream_ms    integer,                               -- of which: waiting on the user's Paperclip (union of parallel requests)
  upstream_calls integer,
  scope          text,                                  -- scope the call required
  grant_id       text,
  client         text,
  instance       text,                                  -- tenant Paperclip host
  user_id        text
);

create index if not exists audit_ts_idx          on bridge.audit_events (ts desc);
create index if not exists audit_kind_name_idx   on bridge.audit_events (kind, name, ts desc);
create index if not exists audit_instance_idx    on bridge.audit_events (instance, ts desc) where instance is not null;
create index if not exists audit_errors_idx      on bridge.audit_events (ts desc) where not ok;

alter table bridge.audit_events enable row level security;
revoke all on bridge.audit_events from public;

do $$
declare r text;
begin
  foreach r in array array['anon', 'authenticated'] loop
    if exists (select 1 from pg_roles where rolname = r) then
      execute format('revoke all on bridge.audit_events from %I', r);
    end if;
  end loop;
end $$;

-- ───── 003_accounts.sql ─────
-- Papercliped accounts: username + secret key, one stored Paperclip connection per account, and the user event log.
-- Nothing here stores a plaintext secret: `secret_hash` is a salted scrypt hash, `sealed_credential` is AES-GCM sealed in the app.

create table if not exists bridge.accounts (
  id            text   primary key,
  username      text   not null,               -- as typed; shown only in the operator's logs
  username_key  text   not null,               -- lowercased; unique
  secret_hash   text   not null,               -- scrypt$N$r$p$salt$hash of the generated secret key
  created_at    bigint not null,
  last_login_at bigint,
  disabled      boolean not null default false
);
create unique index if not exists accounts_username_key_idx on bridge.accounts (username_key);

-- One connection per account. A given Paperclip identity (instance + user id) can belong to only one account.
create table if not exists bridge.account_links (
  account_id         text   primary key references bridge.accounts (id) on delete cascade,
  instance_url       text   not null,
  paperclip_user_id  text,
  sealed_credential  text,                      -- null once dropped (idle expiry / disconnect)
  created_at         bigint not null,
  connected_at       bigint not null,
  last_used_at       bigint not null
);
create unique index if not exists account_links_identity_idx on bridge.account_links (instance_url, paperclip_user_id) where paperclip_user_id is not null;
create index if not exists account_links_idle_idx on bridge.account_links (last_used_at) where sealed_credential is not null;

-- The community log: joined / left / updated / login / ... (see src/accounts/types.ts). `detail` is a short non-sensitive reason.
create table if not exists bridge.user_events (
  id          bigint generated always as identity primary key,
  ts          bigint not null,
  account_id  text,
  username    text,
  kind        text   not null,
  detail      text
);
create index if not exists user_events_ts_idx   on bridge.user_events (ts desc);
create index if not exists user_events_kind_idx on bridge.user_events (kind, ts desc);

-- A row the app rewrites on a timer so a free-tier Supabase project always sees recent write activity.
create table if not exists bridge.heartbeat (
  id integer primary key,
  at bigint  not null
);

alter table bridge.grants       add column if not exists account_id text;
alter table bridge.grants       add column if not exists username   text;
alter table bridge.audit_events add column if not exists username   text;
create index if not exists grants_account_idx on bridge.grants (account_id) where not revoked;
create index if not exists audit_username_idx on bridge.audit_events (username, ts desc) where username is not null;

alter table bridge.accounts      enable row level security;
alter table bridge.account_links enable row level security;
alter table bridge.user_events   enable row level security;
alter table bridge.heartbeat     enable row level security;
revoke all on bridge.accounts, bridge.account_links, bridge.user_events, bridge.heartbeat from public;

do $$
declare r text;
begin
  foreach r in array array['anon', 'authenticated'] loop
    if exists (select 1 from pg_roles where rolname = r) then
      execute format('revoke all on bridge.accounts, bridge.account_links, bridge.user_events, bridge.heartbeat from %I', r);
    end if;
  end loop;
end $$;

-- ───── 004_privacy_panel.sql ─────
-- Privacy (anonymous display names) and the separate operator panel.
--
--  * Accounts can opt in to appear in logs and the panel as a generated alias ("Ann02") and with an anonymous label instead of
--    their Paperclip's hostname. Events and audit rows store only the DISPLAY name, so the panel's database role never sees the
--    real username of an anonymous account. (The service operator with admin access to the base tables still can; see docs/SECURITY.md.)
--  * The bridge writes periodic health samples; the panel reads them, so it can tell when the bridge is down or asleep.
--  * The panel connects with a read-only role that can see only the views and telemetry tables below — never the credential,
--    the secret hash, or real usernames.

alter table bridge.accounts      add column if not exists anonymous boolean not null default false;
alter table bridge.accounts      add column if not exists alias     text;
alter table bridge.account_links add column if not exists instance_label text;   -- the host, or "anon-xxxxxx" for anonymous accounts
create unique index if not exists accounts_alias_idx on bridge.accounts (lower(alias)) where alias is not null;

create table if not exists bridge.node_samples (
  id               bigint generated always as identity primary key,
  ts               bigint not null,
  node             text   not null,
  db_ping_ms       real,
  loop_lag_p99_ms  real,
  rss_mb           real,
  heap_mb          real,
  uptime_s         integer,
  version          text
);
create index if not exists node_samples_ts_idx   on bridge.node_samples (ts desc);
create index if not exists node_samples_node_idx on bridge.node_samples (node, ts desc);
alter table bridge.node_samples enable row level security;
revoke all on bridge.node_samples from public;

-- Views run with the rights of the role that owns them (the migration role), so the panel role needs no access to the base tables.
create or replace view bridge.panel_accounts as
  select id,
         case when anonymous and alias is not null then alias else username end as display_name,
         (anonymous and alias is not null) as anonymous,
         created_at, last_login_at, disabled
    from bridge.accounts;

create or replace view bridge.panel_grants as
  select id, client_name, scopes, created_at, last_used_at, revoked, account_id, username as display_name
    from bridge.grants;

create or replace view bridge.panel_links as
  select account_id, coalesce(instance_label, 'unknown') as instance_label, connected_at, last_used_at, (sealed_credential is not null) as has_credential
    from bridge.account_links;

revoke all on bridge.panel_accounts, bridge.panel_grants, bridge.panel_links from public;

do $$
declare r text;
begin
  foreach r in array array['anon', 'authenticated'] loop
    if exists (select 1 from pg_roles where rolname = r) then
      execute format('revoke all on bridge.node_samples, bridge.panel_accounts, bridge.panel_grants, bridge.panel_links from %I', r);
    end if;
  end loop;
end $$;

-- ───── 005_beta.sql ─────
-- Beta opt-in: accounts that join the beta get the connection manager (/manage) and its management API.
alter table bridge.accounts add column if not exists beta boolean not null default false;

-- ───── 006_two_levels.sql ─────
-- Two access levels: Read only and Full control. The old third level (paperclip:admin) is folded into Full control,
-- which now covers every tool. Existing grants keep working; this only tidies the stored scope lists.
update bridge.grants
   set scopes = array(select distinct s from unnest(array_replace(scopes, 'paperclip:admin', 'paperclip:control')) as s order by s desc)
 where 'paperclip:admin' = any(scopes);

-- ───── 007_control_room.sql ─────
-- Control room: who may do what through Papercliped.
--   accounts.policy  the access switch (api | full | agent) and per-agent overrides, as JSON. Null = Full for every agent.
--   grants.policy    one session's limits (a name, which tools, which agents), as JSON. Null = no limits beyond its access level.
-- The app validates both on the way in and falls back to the safe default on anything it can't read, so old rows need no backfill.
alter table bridge.accounts add column if not exists policy jsonb;
alter table bridge.grants   add column if not exists policy jsonb;

-- Audit rows now also record calls the policy refused (error_class = policy_blocked).
comment on column bridge.audit_events.error_class is 'invalid_input | insufficient_scope | read_only | policy_blocked | upstream_4xx | upstream_5xx | upstream_unreachable | rate_limited | unauthorized | internal';

-- ───── 008_key_rotation.sql ─────
-- Paperclip key rotation: Paperclip expires the board keys it issues (30 days by default), so the bridge renews
-- each stored key about a week before it lapses. credential_expires_at is when Paperclip expires the stored key
-- (ms epoch); null = it never expires (older Paperclip, or a key Paperclip did not issue us), so it is never rotated.
alter table bridge.account_links add column if not exists credential_expires_at bigint;
alter table bridge.grants        add column if not exists credential_expires_at bigint;

-- Keys stored before this migration came from an approved sign-in: assume Paperclip's default 30 days from then.
-- The first rotation check reads the real expiry from Paperclip and corrects it (or clears it if the key never expires).
update bridge.account_links set credential_expires_at = connected_at + 2592000000
 where sealed_credential is not null and credential_expires_at is null;
update bridge.grants set credential_expires_at = created_at + 2592000000
 where sealed_credential is not null and not revoked and credential_expires_at is null;

create index if not exists account_links_expiry_idx on bridge.account_links (credential_expires_at) where sealed_credential is not null;
create index if not exists grants_expiry_idx on bridge.grants (credential_expires_at) where sealed_credential is not null and not revoked;

-- ───── migration bookkeeping ─────
create table if not exists bridge.schema_migrations (version text primary key, applied_at timestamptz not null default now());
alter table bridge.schema_migrations enable row level security;
revoke all on bridge.schema_migrations from public;
do $$ declare r text; begin
  foreach r in array array['anon', 'authenticated'] loop
    if exists (select 1 from pg_roles where rolname = r) then execute format('revoke all on bridge.schema_migrations from %I', r); end if;
  end loop;
end $$;
insert into bridge.schema_migrations (version) values ('001_init.sql'), ('002_audit.sql'), ('003_accounts.sql'), ('004_privacy_panel.sql'), ('005_beta.sql'), ('006_two_levels.sql'), ('007_control_room.sql'), ('008_key_rotation.sql') on conflict (version) do nothing;

commit;
