import { readdirSync, readFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import pg from "pg";
import { sslOption, type PgOptions } from "./oauth/pg-store.js";

const LOCK_ID = 7_351_001; // arbitrary, stable advisory-lock key for "bridge migrations"

/** Apply migrations/*.sql in order, once each, under an advisory lock. Needs a direct or session-mode connection. */
export async function migrate(opts: PgOptions, dir = join(dirname(fileURLToPath(import.meta.url)), "..", "migrations")): Promise<string[]> {
  const client = new pg.Client({ connectionString: opts.connectionString, ssl: sslOption(opts) });
  await client.connect();
  const applied: string[] = [];
  try {
    await client.query("select pg_advisory_lock($1)", [LOCK_ID]);
    await client.query("create schema if not exists bridge");
    await client.query("create table if not exists bridge.schema_migrations (version text primary key, applied_at timestamptz not null default now())");
    const done = new Set((await client.query("select version from bridge.schema_migrations")).rows.map((r) => r.version as string));
    for (const f of readdirSync(dir).filter((f) => /^\d+_.*\.sql$/.test(f)).sort()) {
      if (done.has(f)) continue;
      await client.query("begin");
      try {
        await client.query(readFileSync(join(dir, f), "utf8"));
        await client.query("insert into bridge.schema_migrations (version) values ($1)", [f]);
        await client.query("commit");
        applied.push(f);
      } catch (e) {
        await client.query("rollback");
        throw new Error(`migration ${f} failed: ${(e as Error).message}`);
      }
    }
    // schema_migrations is created outside the numbered files, so lock it down here too.
    await client.query("alter table bridge.schema_migrations enable row level security");
    await client.query("revoke all on bridge.schema_migrations from public");
  } finally {
    await client.query("select pg_advisory_unlock($1)", [LOCK_ID]).catch(() => {});
    await client.end();
  }
  return applied;
}

/**
 * One paste-able script for the Supabase SQL editor: every migration in order, the bookkeeping table, and rows marking each
 * migration as applied (so a later `npm run migrate` is a no-op). Generated — `docs/supabase-schema.sql` is checked against
 * this in the tests so it can never drift from migrations/.
 */
export function consolidatedSql(dir = join(dirname(fileURLToPath(import.meta.url)), "..", "migrations")): string {
  const files = readdirSync(dir).filter((f) => /^\d+_.*\.sql$/.test(f)).sort();
  const parts = files.map((f) => `-- ───── ${f} ─────\n${readFileSync(join(dir, f), "utf8").trim()}\n`);
  return [
    "-- Paperclip Bridge — complete schema for Supabase.",
    "-- GENERATED by `npm run admin -- schema-sql` from migrations/*.sql. Do not edit by hand.",
    "--",
    "-- How to use: Supabase dashboard → SQL Editor → New query → paste this whole file → Run.",
    "-- Safe to run more than once. Afterwards `npm run migrate` reports \"up to date\" because the migrations are recorded below.",
    "-- Then (recommended) create the least-privilege app role: see docs/least-privilege.sql.",
    "",
    "begin;",
    "",
    ...parts,
    "-- ───── migration bookkeeping ─────",
    "create table if not exists bridge.schema_migrations (version text primary key, applied_at timestamptz not null default now());",
    "alter table bridge.schema_migrations enable row level security;",
    "revoke all on bridge.schema_migrations from public;",
    "do $$ declare r text; begin",
    "  foreach r in array array['anon', 'authenticated'] loop",
    "    if exists (select 1 from pg_roles where rolname = r) then execute format('revoke all on bridge.schema_migrations from %I', r); end if;",
    "  end loop;",
    "end $$;",
    `insert into bridge.schema_migrations (version) values ${files.map((f) => `('${f}')`).join(", ")} on conflict (version) do nothing;`,
    "",
    "commit;",
    "",
  ].join("\n");
}
